name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: davisd/go

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build code
      run: make ci
